image:
  repository: 868027517775.dkr.ecr.us-west-2.amazonaws.com/icon-network-exporter
  tag: 8
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  name: icon-network-exporter
  type: ClusterIP

app:
  mainnet_port: 6100
  zicon_port: 6101
  bicon_port: 6102
  testnet_port: 6103

resources:
  request:
    cpu: 250m
    memory: 128Mi
  limit:
    cpu: 500m
    memory: 256Mi

mainnet:
  main_watch_list: []
  sub_watch_list: []

zicon:
  main_watch_list: []
  sub_watch_list: []

bicon:
  main_watch_list: []
  sub_watch_list: []

testnet:
  main_watch_list: []
  sub_watch_list: []
