version: "3.4"
services:
  defaults:
    build:
      context: .
    ports:
      - "6100:6100"
    environment:
      network_name: mainnet
      exporter_port: 6100

  watchlist:
    build:
      context: .
    ports:
      - "6101:6101"
    environment:
      network_name: mainnet
      exporter_port: 6101
      main_watch_list_file: tests/fixtures/main-watch-list.yaml
