version: "3.4"
services:
  mainnet:
    build:
      context: .
      target: prod
    ports:
      - "6100:6100"
    environment:
      network_name: mainnet
      exporter_port: 6100

  zicon:
    build:
      context: .
      target: prod
    ports:
      - "6101:6101"
    environment:
      network_name: zicon
      exporter_port: 6101
  #      end_ranking: 0x22 # 34
  bicon:
    build:
      context: .
      target: prod
    ports:
      - "6102:6102"
    environment:
      network_name: bicon
      exporter_port: 6102
  testnet:
    build:
      context: .
      target: prod
    ports:
      - "6103:6103"
    environment:
      network_name: testnet
      exporter_port: 6103
