apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bicon
  labels:
    icon-network: "bicon"
{{ include "labels" . | indent 4 }}

spec:
  selector:
    matchLabels:
      icon-network: "bicon"
{{ include "selectorLabels" . | indent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        icon-network: "bicon"
{{ include "labels" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-bicon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.request.cpu }}
              memory: {{ .Values.resources.request.memory }}
            limits:
              cpu: {{ .Values.resources.limit.cpu }}
              memory: {{ .Values.resources.limit.memory }}
          ports:
            - containerPort: {{ .Values.app.bicon_port }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.app.bicon_port }}
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.app.bicon_port }}
          env:
            - name: network_name
              value: "bicon"
            - name: exporter_port
              value: {{ .Values.app.bicon_port | quote }}
            - name: main_watch_list
              value: {{ .Values.bicon.main_watch_list | quote }}
            - name: sub_watch_list
              value: {{ .Values.bicon.sub_watch_list | quote }}
