apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mainnet
  labels:
    icon-network: "mainnet"
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.mainnet_port }}
      targetPort: {{ .Values.app.mainnet_port }}
      protocol: TCP
      name: {{ .Values.service.name }}-mainnet
  selector:
    icon-network: "mainnet"
{{ include "selectorLabels" . | indent 4 }}
