apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-testnet
  labels:
    icon-network: "testnet"
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.testnet_port }}
      targetPort: {{ .Values.app.testnet_port }}
      protocol: TCP
      name: {{ .Values.service.name }}-testnet
  selector:
    icon-network: "testnet"
{{ include "selectorLabels" . | indent 4 }}
