apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zicon
  labels:
    icon-network: "zicon"
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.zicon_port }}
      targetPort: {{ .Values.app.zicon_port }}
      protocol: TCP
      name: {{ .Values.service.name }}-zicon
  selector:
    icon-network: "zicon"
{{ include "selectorLabels" . | indent 4 }}
